spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      max-wait: 1000
      default-auto-commit: true
      validation-query: "SELECT 1"
      initial-size: 30
      min-idle: 30
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      connection-init-sqls: "set names utf8mb4"
      driver-class-name: com.mysql.jdbc.Driver
      stat-view-servlet.enabled: false
      web-stat-filter.enabled: false


mybatis:
  type-aliases-package: com.lfwang.reactor.demo.repository.domain
  mapper-locations: mappers/*Mapper.xml

---
spring:
  profiles: dev
